#!/usr/bin/env bash
# checking for parameters

if [$# -lt 4]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# giving parameters

path_to_file=$1
ip=$2
uername=$3
path_to_ssh_key=$4

# disconnecting strict host key

scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:/"


# checking if the transfer was a success
if [ $? -eq 0 ]
then
	echo "FILE WAS TRANSFERED SUCCESSFULLY"
else
	echo "FILE TRANSFER FAILED"
fi
