#!/usr/bin/env bash
# creating a 404 page

sudo apt-get update -y
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

string_for_replacement="server_name -; \nrewrite ^\\/redirect_me https://github.com/Elpluribusunum permanent;" 

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# building a 404 page

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

string_for_replace="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.htmk {\n\troot \/var/www/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# restart nginx after changes made

sudo service nginx restart
