#!/usr/bin/env bash
# Ping an IP address using a Bash script that receives it as an argument.
#* a string is accepted as an argument.
#* Displays Usage: 5-is_the_host_on_the_network
#* {IP_ADDRESS} if no argument passed
#* Five times, ping the IP

if [ "$#" -eq 0 ]; then
	echo 'Usage: 5-is_the_host_on_the_network {IP_ADDRESS}'
else
	ping -c 5 "$1"
fi
