#!/usr/bin/env bash
# "To infinity and beyond" is permanently displayed.
# a two-hour nap between each iteration.
# exhibits "I am invincible!!!" between each iteration.


trap 'echo "I am invincible!!!"' 15
while true;
do
    echo "to infinity and beyond"
    sleep 2
done
